USE DATABASE bi_consumption;
USE SCHEMA raw;

CREATE OR REPLACE TABLE RAW.BI_CONSUMPTION_RAW(
    REF_DATE STRING,
    GEO	VARCHAR(255),
    DGUID VARCHAR(255) PRIMARY KEY,
    ESTIMATES VARCHAR(255),
    CONSUMPTION_CATEGORY VARCHAR(255),
    UOM VARCHAR(255),
    SCALAR_FACTOR VARCHAR(255),
    VALUE FLOAT,
    YEAR INT,
    PREVIOUS_YEAR_VALUE FLOAT,
    YEAR_OVER_YEAR_GROWTH FLOAT
 
);

SELECT * FROM bi_consumption_raw;