CREATE OR REPLACE TABLE STAGING.bi_consumption_staging AS(
    SELECT
    TO_TIMESTAMP(REF_DATE) AS REF_DATE,
    GEO,
    DGUID,
    ESTIMATES,
    CONSUMPTION_CATEGORY,
    UOM,
    SCALAR_FACTOR,
    VALUE,
    YEAR,
    PREVIOUS_YEAR_VALUE,
    YEAR_OVER_YEAR_GROWTH
    FROM RAW.BI_CONSUMPTION_RAW
);

SELECT * FROM STAGING.BI_CONSUMPTION_STAGING;